<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="5" total="9" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-20T17:54:51 TRT" name="Default suite" finished-at="2024-02-20T17:54:59 TRT" duration-ms="8052">
    <groups>
    </groups>
    <test started-at="2024-02-20T17:54:51 TRT" name="Default test" finished-at="2024-02-20T17:54:59 TRT" duration-ms="8052">
      <class name="TestCases.BankTests">
        <test-method is-config="true" signature="setUP()[pri:0, instance:TestCases.BankTests@4fce136b]" started-at="2024-02-20T17:54:51 TRT" name="setUP" finished-at="2024-02-20T17:54:53 TRT" duration-ms="1795" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method signature="BankManagerLogin()[pri:6, instance:TestCases.BankTests@4fce136b]" started-at="2024-02-20T17:54:53 TRT" name="BankManagerLogin" finished-at="2024-02-20T17:54:53 TRT" duration-ms="630" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BankManagerLogin -->
        <test-method signature="AddOneCustomer()[pri:7, instance:TestCases.BankTests@4fce136b]" started-at="2024-02-20T17:54:53 TRT" name="AddOneCustomer" finished-at="2024-02-20T17:54:56 TRT" duration-ms="2988" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddOneCustomer -->
        <test-method signature="openAccount()[pri:8, instance:TestCases.BankTests@4fce136b]" started-at="2024-02-20T17:54:56 TRT" name="openAccount" finished-at="2024-02-20T17:54:59 TRT" duration-ms="2520" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openAccount -->
        <test-method signature="deleteCustomer()[pri:9, instance:TestCases.BankTests@4fce136b]" started-at="2024-02-20T17:54:59 TRT" name="deleteCustomer" finished-at="2024-02-20T17:54:59 TRT" duration-ms="85" status="FAIL">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index 3 out of bounds for length 1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 1
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
at java.base/java.util.Objects.checkIndex(Objects.java:359)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at TestCases.BankTests.deleteCustomer(BankTests.java:168)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteCustomer -->
        <test-method is-config="true" signature="AfterTest()[pri:0, instance:TestCases.BankTests@4fce136b]" started-at="2024-02-20T17:54:59 TRT" name="AfterTest" finished-at="2024-02-20T17:54:59 TRT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterTest -->
      </class> <!-- TestCases.BankTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
